### ISSUE TITLE
doesn't work with the latest datomic free

### ISSUE THREAD

**Issue by hiredman** [Datomic/codeq#2]
when running datomic-free-0.8.3551.zip I get an error about missing a jdbc driver class when trying to import code with codeq.

After adding `(Class/forName "org.h2.Driver")` to the beginning of codeq.core/main it runs fine.

This may be an issue with the datomic client and datomic free missing the loading of the h2 driver.

**Comment by richhickey** [comment]
How are you running with 3551? codeq project.clj only specifies 3546. Did you change that yourself?

**Comment by richhickey** [comment]
When I move project.clj to 3551, do lein clean/deps/uberjar it works fine

**Comment by hiredman** [comment]
I haven't changed codeq's project.clj, and in fact didn't look at it, I just grabbed the latest daomic free zip and ran the free transactor out of it.

most likely running the 3546 peer against the 3551 free transactor?

**Comment by richhickey** [comment]
that worked for me as well

**Comment by hiredman** [comment]
https://gist.github.com/3882511 is a transcript of me checking out codeq, wget'ing datomic, and getting the exception.

I tried to reproduce it on my mac, but I could not even get that far. I ran in to some issue with hornetq.

**Comment by richhickey** [comment]
thanks, I'll try to reproduce that

**Comment by richhickey** [comment]
When I follow your steps exactly, my lein uberjar output is different (are you using lein 2?) and this step fails:
$ java -server -Xmx1g -jar codeq-0.1.0-SNAPSHOT-standalone.jar datomic:free://localhost:4334/git
Unable to access jarfile codeq-0.1.0-SNAPSHOT-standalone.jar

because my jar is put in ./target
but this works:

$ java -server -Xmx1g -jar target/codeq-0.1.0-SNAPSHOT-standalone.jar datomic:free://localhost:4334/git
Importing repo: https://github.com/Datomic/codeq.git as: codeq
Adding repo https://github.com/Datomic/codeq.git
Importing commit: c3bd979cfe65da35253b25cb62aad4271430405c
...

**Comment by richhickey** [comment]
worked also after nuking .m2/repository

**Comment by hiredman** [comment]
I tried it with lein2 and it worked right away.

looking at the project.clj I thought it would just work in lein1, and it does if I add something to load the h2 driver class, very weird.
